export default {
  NAVBAR: {
    AppName: "தேர்தல் போர்டல்",
    Home: "முகப்பு",
    ManifestoPromises: "அறிக்கை வாக்குறுதிகள்",
    Services: "சேவைகள்",
    About: "எங்களைப் பற்றி",
    Help: "உதவி",
  },
  HOME: {
    ElectoralRollSearch: "தேர்தல் பட்டியல் தேடல்",
    FileConverter: "கோப்பு மாற்றி",
    SearchElectoralRoll: "தேர்தல் பட்டியலைத் தேடு",
    SelectState: "மாநிலத்தைத் தேர்ந்தெடு",
    SelectDistrict: "மாவட்டத்தைத் தேர்ந்தெடு",
    SelectConstituency: "தொகுதியைத் தேர்ந்தெடு",
    SelectPollingBooth: "வாக்குச்சாவடியைத் தேர்ந்தெடு",
    Search: "தேடு",
    Reset: "மீட்டமை",
    AvailablePDFs: "கிடைக்கும் PDF கோப்புகள்",
    SlNo: "வ.எண்",
    PollingStationName: "வாக்குச்சாவடியின் பெயர்",
    Address: "முகவரி",
    ConstituencyName: "தொகுதியின் பெயர்",
    ImagePDF: "பட PDF",
    ConvertAction: "மாற்றும் செயல்",
    DownloadConvertedPDF: "மாற்றப்பட்ட PDF ஐப் பதிவிறக்கு",
    ConvertToEditable: "தொகுக்கக்கூடிய வடிவத்திற்கு மாற்று",
    Helpline: "உதவி இலக்கம்: 1950",
    SearchStates: "மாநிலங்களைத் தேடு...",
    NoStatesFound: "மாநிலங்கள் எதுவும் கிடைக்கவில்லை",
    SearchDistricts: "மாவட்டங்களைத் தேடு...",
    NoDistrictsFound: "மாவட்டங்கள் எதுவும் கிடைக்கவில்லை",
    SearchConstituencies: "தொகுதிகளைத் தேடு...",
    NoConstituenciesFound: "தொகுதிகள் எதுவும் கிடைக்கவில்லை",
    SearchPollingBooths: "வாக்குச்சாவடிகளைத் தேடு...",
    NoPollingBoothsFound: "வாக்குச்சாவடிகள் எதுவும் கிடைக்கவில்லை",
    UploadConvertToEditable: "பதிவேற்றி, தொகுக்கக்கூடிய கோப்பாக மாற்று",
    ChooseFileTitle: "கோப்பைத் தேர்ந்தெடு அல்லது இங்கே இழுத்து விடு",
    SupportsPDF: "10MB வரை PDF மட்டுமே ஆதரவு",
    ChooseFile: "கோப்புகளைத் தேர்ந்தெடு",
    UploadConvert: "கோப்புகளைப் பதிவேற்று & மாற்று ",
    PerPage: "(ஒரு பக்கத்திற்கு ₹5)",
    Pages: " பக்கங்கள்",
    Total: "மொத்தம்",
    ClearFiles: "கோப்புகளை அழி",
    PayConvert: "பணம் செலுத்தி மாற்றவும்",
    ConversionCompleted: "மாற்றம் முடிந்தது!",
    ConversionCompletedMessage: "உங்கள் கோப்புகள் வெற்றிகரமாக மாற்றப்பட்டுள்ளன.",
    ConvertedFiles: "மாற்றப்பட்ட கோப்புகள்",
    Download: "பதிவிறக்கு",
    ConvertMoreFiles: "மேலும் கோப்புகளை மாற்று",
    LoadingModalMessage: "PDF ஐ தொகுக்கக்கூடிய வடிவத்திற்கு மாற்றுகிறது...",
    LoadingModalLongerMessage: "இந்த மாற்றும் செயல்முறை வழக்கத்தை விட அதிக நேரம் எடுக்கிறது. தயவுசெய்து திரையைப் புதுப்பிக்கவோ அல்லது மூடவோ வேண்டாம். காத்திருக்கவும்...",
    LoadingModalMessageError: "PDF ஐ மாற்றுவதில் பிழை. மீண்டும் முயற்சிக்கவும்.",
    SearchElectoralRollAlert: "தயவு செய்து மாநிலம், மாவட்டம் மற்றும் தொகுதியைத் தேர்ந்தெடுக்கவும்",
  },
  MANIFESTO: {
    ManifestoPromises: "அறிக்கை வாக்குறுதிகள்",
    NoManifestoPromises: "அறிக்கை வாக்குறுதிகள் எதுவும் காணப்படவில்லை.",
    SNo: "வரிசை எண்",
    Title: "தலைப்பு",
    Description: "விளக்கம்",
    Status: "நிலை",
  },
};