export default {
  NAVBAR: {
    AppName: "ELECTION PORTAL",
    Home: "Home",
    ManifestoPromises: "Manifesto Promises",
    FinancialData: "Financial Data",
    Services: "Services",
    About: "About",
    Help: "Help",
  },
  HOME: {
    ElectoralRollSearch: "Electoral Roll Search",
    FileConverter: "File Converter",
    SearchElectoralRoll: "Search Electoral Roll",
    SelectState: "Select State",
    SelectDistrict: "Select District",
    SelectConstituency: "Select Constituency",
    SelectPollingBooth: "Select Polling Booth",
    Search: "Search",
    Reset: "Reset",
    AvailablePDFs: "Available PDFs",
    SlNo: "SL.NO",
    PollingStationName: "POLLING STATION NAME",
    Address: "ADDRESS",
    ConstituencyName: "CONSTITUENCY NAME",
    ImagePDF: "IMAGE PDF",
    ConvertAction: "CONVERT ACTION",
    DownloadConvertedPDF: "Download Converted PDF",
    ConvertToEditable: "Convert to Editable",
    Helpline: "Helpline: 1950",
    SearchStates: "Search states...",
    NoStatesFound: "No states found",
    SearchDistricts: "Search districts...",
    NoDistrictsFound: "No districts found",
    SearchConstituencies: "Search constituencies...",
    NoConstituenciesFound: "No constituencies found",
    SearchPollingBooths: "Search polling booths...",
    NoPollingBoothsFound: "No polling booths found",
    UploadConvertToEditable: "Upload Image Based PDF & Convert to Editable PDF",
    ChooseFileTitle: "Choose File or Drag & Drop",
    SupportsPDF: "Supports PDF only up to 10MB",
    ChooseFile: "Choose Files",
    UploadConvert: "Upload & Convert Files ",
    PerPage: "(₹5 per page)",
    Pages: " pages",
    Total: "Total",
    ClearFiles: "Clear Files",
    PayConvert: "Pay & Convert",
    ConversionCompleted: "Conversion Completed!",
    ConversionCompletedMessage: "Your files have been successfully converted.",
    ConvertedFiles: "Converted Files",
    Download: "Download",
    ConvertMoreFiles: "Convert More Files",
    LoadingModalMessage: "Converting PDF to editable format...",
    LoadingModalLongerMessage: "This conversion process is taking longer than usual. Do not refresh or close current window. Please wait...",
    LoadingModalMessageError: "Error converting PDF. Please try again.",
    SearchElectoralRollAlert: "Please select State, District and Constituency",
  },
  MANIFESTO: {
    ManifestoPromises: "Manifesto Promises",
    NoManifestoPromises: "No manifesto promises found.",
    SNo: "S.No",
    Title: "Title",
    Description: "Description",
    Status: "Status",
  },
};